// ============================================
// USER & AUTHENTICATION TYPES
// ============================================

export interface User {
  email: string;
  name: string;
  picture?: string;
  role: string; // Fetched from Roles sheet: 'Field Agronomist', 'Sales Executive', 'Manager'
  canAskDb?: boolean;
}

// ============================================
// LEAD (FARMER) TYPE
// ============================================

export interface Lead {
  id: string; // UUID - PRIMARY KEY for joins (e.g., "a3f7b9c1-4d2e-8f5a...")
  rowNumber: number; // Sequential int for displayId (e.g., 416)
  displayId: string; // Human-readable ID (e.g., "LEA-0416") - auto-generated by sheet formula
  createdDate: string; // ISO date string
  createdBy: string; // Email of user who created the lead
  farmerName: string;
  phone: string; // 10-digit phone, stored as TEXT in sheet
  whatsapp?: string;
  village: string;
  taluk: string;
  district: string; // From Lookups sheet (Category='District')
  farmSizeAcres: number;
  cropType: string; // From Lookups sheet (Category='CropType')
  cropAge?: string;
  numPlants?: number;
  irrigationType?: string; // From Lookups sheet (Category='IrrigationType')
  leadSource: string; // From Lookups sheet (Category='LeadSource')
  leadOwner: string; // Email of lead owner (previously assignedTo)
  status: string; // From Lookups sheet (Category='LeadStatus'): New, Contacted, Qualified, Not Qualified
  remarks?: string; // Notes or remarks about the lead
  lastUpdated: string; // ISO date string
  isDeleted: boolean; // Soft delete flag
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// FIELD VISIT TYPE
// ============================================

export interface FieldVisit {
  id: string; // UUID - PRIMARY KEY
  rowNumber: number; // Sequential int
  displayId: string; // e.g., "VIS-0064"
  leadId: string; // Foreign key to Lead.id (UUID)
  scheduledDate: string; // ISO date string
  actualDate?: string;
  visitorId: string; // Email of visiting user
  visitOutcome?: string; // From Lookups sheet (Category='VisitOutcome')
  cropCondition?: string; // From Lookups sheet (Category='CropCondition')
  identifiedProblems?: string[]; // Array of identified diseases/problems
  diagnosisNotes?: string;
  followUpDate?: string;
  status: string; // From Lookups sheet (Category='VisitStatus')
  visitedBy: string[]; // Array of user emails who conducted the visit
  quotationRequested: boolean; // Whether quotation was requested after visit
  assignedTo?: string; // Email of user assigned for quotation follow-up
  attachmentFileId?: string; // Google Drive file ID for visit photos/documents
  createdBy: string;
  createdDate: string;
  isDeleted: boolean;
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// QUOTATION TYPE
// ============================================

export interface Quotation {
  id: string; // UUID - PRIMARY KEY
  rowNumber: number;
  displayId: string; // e.g., "QUO-0006"
  leadId: string; // Foreign key to Lead.id
  visitId?: string; // Optional foreign key to FieldVisit.id
  quoteDate: string;
  quoteAmount: number; // In Rupees
  preparedBy: string; // Email of user
  validUntil: string;
  status: string; // From Lookups sheet (Category='QuotationStatus')
  notes?: string;
  usageInstructions?: string; // Day-by-day product application schedule (How to Use section for print)
  attachmentFileId?: string; // Google Drive file ID for quotation document
  deliveryStatus?: string; // From Lookups sheet (Category='DeliveryStatus'): Pending, Scheduled, Delivered, Partial
  deliveryDate?: string; // When material was/will be delivered
  lastUpdated: string;
  isDeleted: boolean;
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// PAYMENT TYPE
// ============================================

export interface Payment {
  id: string; // UUID - PRIMARY KEY
  rowNumber: number;
  displayId: string; // e.g., "PAY-0001"
  quoteId: string; // Foreign key to Quotation.id
  paymentDate: string;
  paymentAmount: number; // In Rupees
  paymentType: string; // From Lookups sheet (Category='PaymentType'): 'Advance', 'Partial', 'Final'
  paymentMethod: string; // From Lookups sheet (Category='PaymentMethod'): 'Cash', 'UPI', 'Bank Transfer'
  transactionRef?: string;
  receivedBy: string; // Email of user
  notes?: string;
  isDeleted: boolean;
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// PRODUCT TYPE
// ============================================

export interface Product {
  id: string; // UUID - PRIMARY KEY
  sku: string; // Unique product SKU
  name: string; // Product name in English
  nameKannada?: string; // Product name in Kannada
  description?: string; // Product description / benefits
  dosage?: string; // Application rate, e.g. "50ml/200 Liters"
  unitPrice: number; // Price per unit
  unit: string; // Unit of measurement: kg, litre, unit, bag, bottle, pack, etc.
  category?: string; // For grouping: e.g., 'Drenching', 'Spraying'
  isActive: boolean; // Whether product is available for selection
  displayOrder: number; // For sorting in dropdowns
  createdAt: string;
  updatedAt: string;
}

// ============================================
// QUOTATION LINE ITEM TYPE
// ============================================

export interface QuotationLineItem {
  id: string; // UUID - PRIMARY KEY
  quotationId: string; // FK to Quotation.id
  productId: string; // FK to Product.id
  productName: string; // Snapshot of product name at quote time
  unitPrice: number; // Snapshot of unit price at quote time
  quantity: number;
  subtotal: number; // GENERATED: unitPrice * quantity (read-only)
  notes?: string;
  displayOrder: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Lightweight line item row used in QuotationModal and QuotationPDF.
 * Subset of QuotationLineItem without DB-only fields.
 */
export interface LineItemRow {
  id?: string;
  productId: string;
  productName: string;
  unitPrice: number;
  quantity: number;
  notes: string;
  displayOrder: number;
}

// ============================================
// LOOKUP VALUES TYPE (Master Data)
// ============================================

export interface LookupValue {
  category: string; // e.g., 'District', 'CropType', 'LeadSource', 'Taluk'
  value: string; // e.g., 'Hassan', 'Arecanut', 'Referral'
  displayOrder: number; // For sorting in dropdowns
  active: boolean; // Is this value currently active?
  parentValue?: string; // For hierarchical lookups (e.g., Taluk's parent District)
}

// Taluk with its parent district for cascade filtering
export interface TalukWithDistrict {
  taluk: string;
  district: string; // Parent district name
}

// Organized lookup values by category (for easy access in UI)
export interface LookupData {
  districts: string[];
  taluks: TalukWithDistrict[]; // Taluks with their parent districts for cascade filtering
  cropTypes: string[];
  leadSources: string[];
  leadStatuses: string[];
  irrigationTypes: string[];
  visitOutcomes: string[];
  visitStatuses: string[];
  cropConditions: string[];
  quotationStatuses: string[];
  deliveryStatuses: string[]; // Pending, Scheduled, Delivered, Partial
  paymentTypes: string[];
  paymentMethods: string[];
}

// ============================================
// ROLE MAPPING TYPE
// ============================================

export interface RoleMapping {
  email: string;
  role: string;
}

// ============================================
// AUDIT LOG TYPE
// ============================================

export interface AuditLog {
  timestamp: string; // ISO date string
  userEmail: string;
  action: 'CREATE' | 'UPDATE' | 'DELETE' | 'RESTORE';
  sheet: 'Leads' | 'FieldVisits' | 'Quotations' | 'Payments';
  recordId: string; // The UUID of the affected record
  oldValue?: string; // JSON string of old data (for UPDATE/DELETE)
  newValue?: string; // JSON string of new data (for CREATE/UPDATE)
  ipAddress?: string;
}

// ============================================
// FORM INPUT TYPES (for creating/editing)
// ============================================

// When creating a new lead, we don't need id, rowNumber, displayId, etc.
export type LeadFormInput = Omit<
  Lead,
  'id' | 'rowNumber' | 'displayId' | 'createdDate' | 'lastUpdated' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

export type VisitFormInput = Omit<
  FieldVisit,
  'id' | 'rowNumber' | 'displayId' | 'createdDate' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

export type QuotationFormInput = Omit<
  Quotation,
  'id' | 'rowNumber' | 'displayId' | 'lastUpdated' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

export type PaymentFormInput = Omit<
  Payment,
  'id' | 'rowNumber' | 'displayId' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

export type ProductFormInput = Omit<Product, 'id' | 'createdAt' | 'updatedAt'>;

export type LineItemFormInput = Omit<QuotationLineItem, 'id' | 'subtotal' | 'createdAt' | 'updatedAt'>;

// ============================================
// API RESPONSE TYPES
// ============================================

// Raw data from Google Sheets API (2D array)
export type SheetRowData = (string | number | boolean)[][];

// Response from our Apps Script ID generation endpoint
export interface IdGenerationResponse {
  number: number;
  error?: string;
}

// Pagination for large lists
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

// Filter options for lead list
export interface LeadFilters {
  status?: string;
  district?: string;
  assignedTo?: string;
  leadSource?: string;
  cropType?: string;
  searchQuery?: string; // Search by farmer name, phone, village
}

// Filter options for visit list
export interface VisitFilters {
  status?: string;
  visitorId?: string;
  dateFrom?: string;
  dateTo?: string;
  leadId?: string; // Filter visits for a specific lead
}

// Dashboard stats
export interface DashboardStats {
  totalRevenue: number;
  thisMonthRevenue: number;
  pendingAmount: number;
  collectionRate: number; // Collection rate %
  totalLeads: number;
  newLeads: number;
  quotationsSent: number;
  quotationsAccepted: number;
  conversionRate: number; // Quote to acceptance conversion %
  expiringQuotes: Array<{ id: string; displayId: string; validUntil: string; quoteAmount: number; leadId: string; status: string }>;
  upcomingVisits: Array<{ id: string; displayId: string; scheduledDate: string; leadId: string }>;
  recentLeads: Array<{ id: string; displayId: string; farmerName: string; createdDate: string; district: string; status: string }>;
  recentPayments: Array<{ id: string; displayId: string; paymentAmount: number; paymentDate: string; paymentMethod: string; quoteId: string }>;
}

// ============================================
// GOOGLE SHEETS STRUCTURE
// ============================================

// Sheet names (for reference)
export const SHEET_NAMES = {
  LEADS: 'Leads',
  FIELD_VISITS: 'FieldVisits',
  QUOTATIONS: 'Quotations',
  PAYMENTS: 'Payments',
  LOOKUPS: 'Lookups',
  ROLES: 'Roles',
  AUDIT_LOG: 'AuditLog',
  METADATA: 'Metadata',
} as const;

// Column mapping for Leads sheet
// A=id, B=rowNumber, C=displayId, D=createdDate, E=farmerName, F=phone, G=whatsapp,
// H=village, I=taluk, J=district, K=farmSizeAcres, L=cropType, M=cropAge,
// N=numPlants, O=irrigationType, P=leadSource, Q=leadOwner, R=status, S=remarks,
// T=lastUpdated, U=isDeleted, V=deletedBy, W=deletedDate, X=deleteReason
export const LEAD_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  CREATED_DATE: 'D',
  FARMER_NAME: 'E',
  PHONE: 'F',
  WHATSAPP: 'G',
  VILLAGE: 'H',
  TALUK: 'I',
  DISTRICT: 'J',
  FARM_SIZE_ACRES: 'K',
  CROP_TYPE: 'L',
  CROP_AGE: 'M',
  NUM_PLANTS: 'N',
  IRRIGATION_TYPE: 'O',
  LEAD_SOURCE: 'P',
  LEAD_OWNER: 'Q',
  STATUS: 'R',
  REMARKS: 'S',
  LAST_UPDATED: 'T',
  IS_DELETED: 'U',
  DELETED_BY: 'V',
  DELETED_DATE: 'W',
  DELETE_REASON: 'X',
} as const;

// Column mapping for FieldVisits sheet
// A=id, B=rowNumber, C=displayId, D=leadId, E=scheduledDate, F=actualDate,
// G=visitorId, H=visitOutcome, I=cropCondition, J=identifiedProblems, K=diagnosisNotes,
// L=followUpDate, M=status, N=visitedBy, O=quotationRequested,
// P=assignedTo, Q=attachmentFileId, R=createdBy, S=createdDate, T=isDeleted, U=deletedBy, V=deletedDate, W=deleteReason
export const FIELD_VISIT_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  LEAD_ID: 'D',
  SCHEDULED_DATE: 'E',
  ACTUAL_DATE: 'F',
  VISITOR_ID: 'G',
  VISIT_OUTCOME: 'H',
  CROP_CONDITION: 'I',
  IDENTIFIED_PROBLEMS: 'J',
  DIAGNOSIS_NOTES: 'K',
  FOLLOW_UP_DATE: 'L',
  STATUS: 'M',
  VISITED_BY: 'N',
  QUOTATION_REQUESTED: 'O',
  ASSIGNED_TO: 'P',
  ATTACHMENT_FILE_ID: 'Q',
  CREATED_BY: 'R',
  CREATED_DATE: 'S',
  IS_DELETED: 'T',
  DELETED_BY: 'U',
  DELETED_DATE: 'V',
  DELETE_REASON: 'W',
} as const;

// Disease and problem identification options (for field visits)
export const CROP_PROBLEMS = [
  { en: 'Physiological Disorder', kn: 'ಹಿಡಿಮುಂಡಿಗೆ' },
  { en: 'Secondary & Micro Nutrients Deficiency', kn: 'ಸಮಗ್ರ ಪೋಷಕಾಂಶಗಳ ಕೊರತೆ' },
  { en: 'Potash Deficiency', kn: 'ಪೊಟ್ಯಾಶ್ ಕೊರತೆ' },
  { en: 'Excess Nitrogen', kn: 'ಹೆಚ್ಚುವರಿ ಸಾರಜನಕ' },
  { en: 'Inflorescence Dieback', kn: 'ಹಿಂಗಾರ ಒಣಗುವಿಕೆ' },
  { en: 'Fruit Dropping', kn: 'ಹರಳು ಉದುರುವುದು' },
  { en: 'Nut Dropping', kn: 'ಕಾಯಿ ಉದುರುವುದು' },
  { en: 'Nut Rot Disease', kn: 'ಅಡಿಕೆ ಕೊಳೆ ರೋಗ' },
  { en: 'Leaf Spot Disease', kn: 'ಎಲೆ ಚುಕ್ಕೆ ರೋಗ' },
  { en: 'Crown Rot Disease', kn: 'ಸುಳಿ ಕೊಳೆ ರೋಗ' },
  { en: 'Ganoderma Disease', kn: 'ಅಣಬೆ ರೋಗ' },
  { en: 'Root Grubs', kn: 'ಬೇರು ಹುಳು ಸಮಸ್ಯೆ' },
  { en: 'Leaf Blight Disease', kn: 'ಎಲೆ ಸೊರಗು ರೋಗ' },
  { en: 'Spindle Bug', kn: 'ಸುಳಿ ತಿಗಣೆ' },
  { en: 'Red Mites', kn: 'ಕೆಂಪು ಹುಳ' },
  { en: 'Yellow Leaf Disease', kn: 'ಹಳದಿ ಎಲೆ ರೋಗ' },
  { en: 'Abnormal Growth Without Production', kn: 'ಅಡಿಕೆ ಮರದಲ್ಲಿ ಉತ್ಪಾದನೆಯಿಲ್ಲದೆ ಅಸಹಜ ಬೆಳವಣಿಗೆ' },
  { en: 'Hormone Imbalance', kn: 'ಹಾರ್ಮೋನ್ ಅಸಮತೋಲನ' },
  { en: 'Lack of Storage', kn: 'ಶೇಖರಣೆಯ ಕೊರತೆ' },
  { en: 'Root Rot Disease', kn: 'ಬೇರು ಕೊಳೆ ರೋಗ' },
] as const;

// Column mapping for Quotations sheet
// A=id, B=rowNumber, C=displayId, D=leadId, E=visitId, F=quoteDate,
// G=quoteAmount, H=preparedBy, I=validUntil, J=status, K=notes,
// L=attachmentFileId, M=deliveryStatus, N=deliveryDate, O=lastUpdated,
// P=isDeleted, Q=deletedBy, R=deletedDate, S=deleteReason
export const QUOTATION_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  LEAD_ID: 'D',
  VISIT_ID: 'E',
  QUOTE_DATE: 'F',
  QUOTE_AMOUNT: 'G',
  PREPARED_BY: 'H',
  VALID_UNTIL: 'I',
  STATUS: 'J',
  NOTES: 'K',
  ATTACHMENT_FILE_ID: 'L',
  DELIVERY_STATUS: 'M',
  DELIVERY_DATE: 'N',
  LAST_UPDATED: 'O',
  IS_DELETED: 'P',
  DELETED_BY: 'Q',
  DELETED_DATE: 'R',
  DELETE_REASON: 'S',
} as const;

// Column mapping for Payments sheet
// A=id, B=rowNumber, C=displayId, D=quoteId, E=paymentDate, F=paymentAmount,
// G=paymentType, H=paymentMethod, I=transactionRef, J=receivedBy, K=notes,
// L=isDeleted, M=deletedBy, N=deletedDate, O=deleteReason
export const PAYMENT_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  QUOTE_ID: 'D',
  PAYMENT_DATE: 'E',
  PAYMENT_AMOUNT: 'F',
  PAYMENT_TYPE: 'G',
  PAYMENT_METHOD: 'H',
  TRANSACTION_REF: 'I',
  RECEIVED_BY: 'J',
  NOTES: 'K',
  IS_DELETED: 'L',
  DELETED_BY: 'M',
  DELETED_DATE: 'N',
  DELETE_REASON: 'O',
} as const;
