// ============================================
// USER & AUTHENTICATION TYPES
// ============================================

export interface User {
  email: string;
  name: string;
  picture?: string;
  role: string; // Fetched from Roles sheet: 'Field Agronomist', 'Sales Executive', 'Manager'
}

// ============================================
// LEAD (FARMER) TYPE
// ============================================

export interface Lead {
  id: string; // UUID - PRIMARY KEY for joins (e.g., "a3f7b9c1-4d2e-8f5a...")
  rowNumber: number; // Sequential int for displayId (e.g., 416)
  displayId: string; // Human-readable ID (e.g., "LEA-0416") - auto-generated by sheet formula
  createdDate: string; // ISO date string
  farmerName: string;
  phone: string; // 10-digit phone, stored as TEXT in sheet
  whatsapp?: string;
  village: string;
  taluk: string;
  district: string; // From Lookups sheet (Category='District')
  farmSizeAcres: number;
  cropType: string; // From Lookups sheet (Category='CropType')
  cropAge?: string;
  numPlants?: number;
  irrigationType?: string; // From Lookups sheet (Category='IrrigationType')
  leadSource: string; // From Lookups sheet (Category='LeadSource')
  leadOwner: string; // Email of lead owner (previously assignedTo)
  status: string; // From Lookups sheet (Category='LeadStatus'): New, Contacted, Qualified, Not Qualified
  remarks?: string; // Notes or remarks about the lead
  lastUpdated: string; // ISO date string
  isDeleted: boolean; // Soft delete flag
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// FIELD VISIT TYPE
// ============================================

export interface FieldVisit {
  id: string; // UUID - PRIMARY KEY
  rowNumber: number; // Sequential int
  displayId: string; // e.g., "VIS-0064"
  leadId: string; // Foreign key to Lead.id (UUID)
  scheduledDate: string; // ISO date string
  actualDate?: string;
  visitorId: string; // Email of visiting user
  visitOutcome?: string; // From Lookups sheet (Category='VisitOutcome')
  cropCondition?: string; // From Lookups sheet (Category='CropCondition')
  diagnosisNotes?: string;
  followUpDate?: string;
  status: string; // From Lookups sheet (Category='VisitStatus')
  visitedBy: string[]; // Array of user emails who conducted the visit
  quotationRequested: boolean; // Whether quotation was requested after visit
  assignedTo?: string; // Email of user assigned for quotation follow-up
  attachmentFileId?: string; // Google Drive file ID for visit photos/documents
  createdBy: string;
  createdDate: string;
  isDeleted: boolean;
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// QUOTATION TYPE
// ============================================

export interface Quotation {
  id: string; // UUID - PRIMARY KEY
  rowNumber: number;
  displayId: string; // e.g., "QUO-0006"
  leadId: string; // Foreign key to Lead.id
  visitId?: string; // Optional foreign key to FieldVisit.id
  quoteDate: string;
  quoteAmount: number; // In Rupees
  preparedBy: string; // Email of user
  validUntil: string;
  status: string; // From Lookups sheet (Category='QuotationStatus')
  notes?: string;
  attachmentFileId?: string; // Google Drive file ID for quotation document
  deliveryStatus?: string; // From Lookups sheet (Category='DeliveryStatus'): Pending, Scheduled, Delivered, Partial
  deliveryDate?: string; // When material was/will be delivered
  lastUpdated: string;
  isDeleted: boolean;
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// PAYMENT TYPE
// ============================================

export interface Payment {
  id: string; // UUID - PRIMARY KEY
  rowNumber: number;
  displayId: string; // e.g., "PAY-0001"
  quoteId: string; // Foreign key to Quotation.id
  paymentDate: string;
  paymentAmount: number; // In Rupees
  paymentType: string; // From Lookups sheet (Category='PaymentType'): 'Advance', 'Partial', 'Final'
  paymentMethod: string; // From Lookups sheet (Category='PaymentMethod'): 'Cash', 'UPI', 'Bank Transfer'
  transactionRef?: string;
  receivedBy: string; // Email of user
  notes?: string;
  isDeleted: boolean;
  deletedBy?: string;
  deletedDate?: string;
  deleteReason?: string;
}

// ============================================
// LOOKUP VALUES TYPE (Master Data)
// ============================================

export interface LookupValue {
  category: string; // e.g., 'District', 'CropType', 'LeadSource', 'Taluk'
  value: string; // e.g., 'Hassan', 'Arecanut', 'Referral'
  displayOrder: number; // For sorting in dropdowns
  active: boolean; // Is this value currently active?
  parentValue?: string; // For hierarchical lookups (e.g., Taluk's parent District)
}

// Taluk with its parent district for cascade filtering
export interface TalukWithDistrict {
  taluk: string;
  district: string; // Parent district name
}

// Organized lookup values by category (for easy access in UI)
export interface LookupData {
  districts: string[];
  taluks: TalukWithDistrict[]; // Taluks with their parent districts for cascade filtering
  cropTypes: string[];
  leadSources: string[];
  leadStatuses: string[];
  irrigationTypes: string[];
  visitOutcomes: string[];
  visitStatuses: string[];
  cropConditions: string[];
  quotationStatuses: string[];
  deliveryStatuses: string[]; // Pending, Scheduled, Delivered, Partial
  paymentTypes: string[];
  paymentMethods: string[];
}

// ============================================
// ROLE MAPPING TYPE
// ============================================

export interface RoleMapping {
  email: string;
  role: string;
}

// ============================================
// AUDIT LOG TYPE
// ============================================

export interface AuditLog {
  timestamp: string; // ISO date string
  userEmail: string;
  action: 'CREATE' | 'UPDATE' | 'DELETE' | 'RESTORE';
  sheet: 'Leads' | 'FieldVisits' | 'Quotations' | 'Payments';
  recordId: string; // The UUID of the affected record
  oldValue?: string; // JSON string of old data (for UPDATE/DELETE)
  newValue?: string; // JSON string of new data (for CREATE/UPDATE)
  ipAddress?: string;
}

// ============================================
// FORM INPUT TYPES (for creating/editing)
// ============================================

// When creating a new lead, we don't need id, rowNumber, displayId, etc.
export type LeadFormInput = Omit<
  Lead,
  'id' | 'rowNumber' | 'displayId' | 'createdDate' | 'lastUpdated' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

export type VisitFormInput = Omit<
  FieldVisit,
  'id' | 'rowNumber' | 'displayId' | 'createdDate' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

export type QuotationFormInput = Omit<
  Quotation,
  'id' | 'rowNumber' | 'displayId' | 'lastUpdated' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

export type PaymentFormInput = Omit<
  Payment,
  'id' | 'rowNumber' | 'displayId' | 'isDeleted' | 'deletedBy' | 'deletedDate' | 'deleteReason'
>;

// ============================================
// API RESPONSE TYPES
// ============================================

// Raw data from Google Sheets API (2D array)
export type SheetRowData = (string | number | boolean)[][];

// Response from our Apps Script ID generation endpoint
export interface IdGenerationResponse {
  number: number;
  error?: string;
}

// Pagination for large lists
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

// Filter options for lead list
export interface LeadFilters {
  status?: string;
  district?: string;
  assignedTo?: string;
  leadSource?: string;
  cropType?: string;
  searchQuery?: string; // Search by farmer name, phone, village
}

// Filter options for visit list
export interface VisitFilters {
  status?: string;
  visitorId?: string;
  dateFrom?: string;
  dateTo?: string;
  leadId?: string; // Filter visits for a specific lead
}

// Dashboard stats
export interface DashboardStats {
  totalLeads: number;
  activeLeads: number;
  totalVisits: number;
  totalQuotes: number;
  totalRevenue: number;
  conversionRate: number; // Lead to Sale conversion %
  leadsThisMonth: number;
  visitsThisMonth: number;
  quotesThisMonth: number;
}

// ============================================
// GOOGLE SHEETS STRUCTURE
// ============================================

// Sheet names (for reference)
export const SHEET_NAMES = {
  LEADS: 'Leads',
  FIELD_VISITS: 'FieldVisits',
  QUOTATIONS: 'Quotations',
  PAYMENTS: 'Payments',
  LOOKUPS: 'Lookups',
  ROLES: 'Roles',
  AUDIT_LOG: 'AuditLog',
  METADATA: 'Metadata',
} as const;

// Column mapping for Leads sheet
// A=id, B=rowNumber, C=displayId, D=createdDate, E=farmerName, F=phone, G=whatsapp,
// H=village, I=taluk, J=district, K=farmSizeAcres, L=cropType, M=cropAge,
// N=numPlants, O=irrigationType, P=leadSource, Q=leadOwner, R=status, S=remarks,
// T=lastUpdated, U=isDeleted, V=deletedBy, W=deletedDate, X=deleteReason
export const LEAD_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  CREATED_DATE: 'D',
  FARMER_NAME: 'E',
  PHONE: 'F',
  WHATSAPP: 'G',
  VILLAGE: 'H',
  TALUK: 'I',
  DISTRICT: 'J',
  FARM_SIZE_ACRES: 'K',
  CROP_TYPE: 'L',
  CROP_AGE: 'M',
  NUM_PLANTS: 'N',
  IRRIGATION_TYPE: 'O',
  LEAD_SOURCE: 'P',
  LEAD_OWNER: 'Q',
  STATUS: 'R',
  REMARKS: 'S',
  LAST_UPDATED: 'T',
  IS_DELETED: 'U',
  DELETED_BY: 'V',
  DELETED_DATE: 'W',
  DELETE_REASON: 'X',
} as const;

// Column mapping for FieldVisits sheet
// A=id, B=rowNumber, C=displayId, D=leadId, E=scheduledDate, F=actualDate,
// G=visitorId, H=visitOutcome, I=cropCondition, J=diagnosisNotes,
// K=followUpDate, L=status, M=visitedBy, N=quotationRequested,
// O=assignedTo, P=attachmentFileId, Q=createdBy, R=createdDate, S=isDeleted, T=deletedBy, U=deletedDate, V=deleteReason
export const FIELD_VISIT_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  LEAD_ID: 'D',
  SCHEDULED_DATE: 'E',
  ACTUAL_DATE: 'F',
  VISITOR_ID: 'G',
  VISIT_OUTCOME: 'H',
  CROP_CONDITION: 'I',
  DIAGNOSIS_NOTES: 'J',
  FOLLOW_UP_DATE: 'K',
  STATUS: 'L',
  VISITED_BY: 'M',
  QUOTATION_REQUESTED: 'N',
  ASSIGNED_TO: 'O',
  ATTACHMENT_FILE_ID: 'P',
  CREATED_BY: 'Q',
  CREATED_DATE: 'R',
  IS_DELETED: 'S',
  DELETED_BY: 'T',
  DELETED_DATE: 'U',
  DELETE_REASON: 'V',
} as const;

// Column mapping for Quotations sheet
// A=id, B=rowNumber, C=displayId, D=leadId, E=visitId, F=quoteDate,
// G=quoteAmount, H=preparedBy, I=validUntil, J=status, K=notes,
// L=attachmentFileId, M=deliveryStatus, N=deliveryDate, O=lastUpdated,
// P=isDeleted, Q=deletedBy, R=deletedDate, S=deleteReason
export const QUOTATION_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  LEAD_ID: 'D',
  VISIT_ID: 'E',
  QUOTE_DATE: 'F',
  QUOTE_AMOUNT: 'G',
  PREPARED_BY: 'H',
  VALID_UNTIL: 'I',
  STATUS: 'J',
  NOTES: 'K',
  ATTACHMENT_FILE_ID: 'L',
  DELIVERY_STATUS: 'M',
  DELIVERY_DATE: 'N',
  LAST_UPDATED: 'O',
  IS_DELETED: 'P',
  DELETED_BY: 'Q',
  DELETED_DATE: 'R',
  DELETE_REASON: 'S',
} as const;

// Column mapping for Payments sheet
// A=id, B=rowNumber, C=displayId, D=quoteId, E=paymentDate, F=paymentAmount,
// G=paymentType, H=paymentMethod, I=transactionRef, J=receivedBy, K=notes,
// L=isDeleted, M=deletedBy, N=deletedDate, O=deleteReason
export const PAYMENT_COLUMNS = {
  ID: 'A',
  ROW_NUMBER: 'B',
  DISPLAY_ID: 'C',
  QUOTE_ID: 'D',
  PAYMENT_DATE: 'E',
  PAYMENT_AMOUNT: 'F',
  PAYMENT_TYPE: 'G',
  PAYMENT_METHOD: 'H',
  TRANSACTION_REF: 'I',
  RECEIVED_BY: 'J',
  NOTES: 'K',
  IS_DELETED: 'L',
  DELETED_BY: 'M',
  DELETED_DATE: 'N',
  DELETE_REASON: 'O',
} as const;
