-- Attendance & Travel Tracking
-- Tracks daily check-in/check-out for field workers with GPS and km-based incentives

-- ============================================
-- ATTENDANCE TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS attendance (
  id UUID PRIMARY KEY,
  row_number INTEGER GENERATED BY DEFAULT AS IDENTITY,
  display_id TEXT GENERATED ALWAYS AS ('ATT-' || LPAD(row_number::TEXT, 4, '0')) STORED,

  -- Core
  user_email TEXT NOT NULL,
  attendance_date DATE NOT NULL,

  -- Check-in
  check_in_time TIMESTAMPTZ NOT NULL,
  check_in_lat DOUBLE PRECISION,
  check_in_lng DOUBLE PRECISION,
  check_in_address TEXT,

  -- Check-out (null until worker checks out)
  check_out_time TIMESTAMPTZ,
  check_out_lat DOUBLE PRECISION,
  check_out_lng DOUBLE PRECISION,
  check_out_address TEXT,

  -- Travel
  km_traveled NUMERIC(7,2) DEFAULT 0,
  travel_notes TEXT,

  -- Incentive
  incentive_rate NUMERIC(6,2),
  incentive_amount NUMERIC(10,2) GENERATED ALWAYS AS (km_traveled * incentive_rate) STORED,

  -- Status
  status TEXT NOT NULL DEFAULT 'checked-in',

  -- Audit
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_updated TIMESTAMPTZ DEFAULT NOW(),

  -- Soft delete
  is_deleted BOOLEAN DEFAULT FALSE,
  deleted_by TEXT,
  deleted_date TIMESTAMPTZ,
  delete_reason TEXT,

  -- One attendance per worker per day
  CONSTRAINT attendance_unique_per_day UNIQUE (user_email, attendance_date)
);

-- ============================================
-- ATTENDANCE STOPS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS attendance_stops (
  id UUID PRIMARY KEY,
  attendance_id UUID NOT NULL REFERENCES attendance(id) ON DELETE CASCADE,
  stop_order INTEGER NOT NULL,
  stop_time TIMESTAMPTZ NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  address TEXT,
  km_from_previous NUMERIC(7,2) DEFAULT 0,
  is_manual_km BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookups
CREATE INDEX idx_attendance_stops_attendance_id ON attendance_stops(attendance_id);
CREATE INDEX idx_attendance_user_date ON attendance(user_email, attendance_date);
CREATE INDEX idx_attendance_date ON attendance(attendance_date);

-- ============================================
-- ATTENDANCE CONFIG TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS attendance_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  config_key TEXT UNIQUE NOT NULL,
  config_value TEXT NOT NULL,
  updated_by TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Default incentive rate: Rs 3.00 per km
INSERT INTO attendance_config (config_key, config_value)
VALUES ('incentive_rate_per_km', '3.00')
ON CONFLICT (config_key) DO NOTHING;

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_config ENABLE ROW LEVEL SECURITY;

-- Attendance: workers see own, managers/admins see all
CREATE POLICY "Users can view own attendance"
  ON attendance FOR SELECT
  USING (
    user_email = auth.jwt() ->> 'email'
    OR EXISTS (
      SELECT 1 FROM allowed_users
      WHERE email = auth.jwt() ->> 'email'
      AND role IN ('Manager', 'Admin')
    )
  );

CREATE POLICY "Users can insert own attendance"
  ON attendance FOR INSERT
  WITH CHECK (user_email = auth.jwt() ->> 'email');

CREATE POLICY "Users can update own or admin can update any"
  ON attendance FOR UPDATE
  USING (
    user_email = auth.jwt() ->> 'email'
    OR EXISTS (
      SELECT 1 FROM allowed_users
      WHERE email = auth.jwt() ->> 'email'
      AND role = 'Admin'
    )
  );

-- Attendance stops: same policy as parent attendance
CREATE POLICY "Users can view own attendance stops"
  ON attendance_stops FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM attendance
      WHERE attendance.id = attendance_stops.attendance_id
      AND (
        attendance.user_email = auth.jwt() ->> 'email'
        OR EXISTS (
          SELECT 1 FROM allowed_users
          WHERE email = auth.jwt() ->> 'email'
          AND role IN ('Manager', 'Admin')
        )
      )
    )
  );

CREATE POLICY "Users can insert own attendance stops"
  ON attendance_stops FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM attendance
      WHERE attendance.id = attendance_stops.attendance_id
      AND attendance.user_email = auth.jwt() ->> 'email'
    )
  );

CREATE POLICY "Users can update own attendance stops"
  ON attendance_stops FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM attendance
      WHERE attendance.id = attendance_stops.attendance_id
      AND (
        attendance.user_email = auth.jwt() ->> 'email'
        OR EXISTS (
          SELECT 1 FROM allowed_users
          WHERE email = auth.jwt() ->> 'email'
          AND role = 'Admin'
        )
      )
    )
  );

CREATE POLICY "Admin can delete attendance stops"
  ON attendance_stops FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM allowed_users
      WHERE email = auth.jwt() ->> 'email'
      AND role = 'Admin'
    )
  );

-- Config: anyone can read, only admin can write
CREATE POLICY "Anyone can read config"
  ON attendance_config FOR SELECT
  USING (true);

CREATE POLICY "Only admin can update config"
  ON attendance_config FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM allowed_users
      WHERE email = auth.jwt() ->> 'email'
      AND role = 'Admin'
    )
  );
