/**
 * ID Generation Utilities
 *
 * This module provides functions for generating unique identifiers used across the application.
 *
 * Triple-ID System:
 * 1. UUID (id): Primary key for database relationships, never changes
 * 2. Row Number (rowNumber): Sequential integer fetched from Google Apps Script
 * 3. Display ID (displayId): Human-readable ID generated by Google Sheets formula
 *
 * Example: Lead with UUID "a3f7b9c1-4d2e-8f5a-1234567890ab" gets rowNumber 416
 *          which becomes displayId "LEA-0416" via sheet formula
 */

/**
 * Generates a UUID v4 (random UUID)
 * Uses the browser's built-in crypto.randomUUID() API
 *
 * @returns A UUID string (e.g., "a3f7b9c1-4d2e-8f5a-1234567890ab")
 */
export function generateUUID(): string {
  // Use browser's built-in crypto API (supported in all modern browsers)
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }

  // Fallback for older browsers (shouldn't be needed with modern browsers)
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Entity types that have sequential row numbers
 */
export type EntityType = 'Lead' | 'FieldVisit' | 'Quotation' | 'Payment';

/**
 * Maps entity types to their display ID prefixes
 */
const DISPLAY_ID_PREFIXES: Record<EntityType, string> = {
  Lead: 'LEA',
  FieldVisit: 'VIS',
  Quotation: 'QUO',
  Payment: 'PAY',
};

/**
 * Calls Google Apps Script to get the next sequential row number
 * This uses LockService to ensure atomic increment even with concurrent users
 *
 * @param entityType - The type of entity (Lead, FieldVisit, etc.)
 * @returns Promise that resolves to the next available row number
 *
 * @example
 * const rowNumber = await getNextRowNumber('Lead');
 * // Returns: 416
 */
export async function getNextRowNumber(entityType: EntityType): Promise<number> {
  // TODO: Implement Apps Script API call
  // This will be implemented when we set up Google Apps Script
  // For now, throwing an error as a placeholder

  throw new Error(
    `getNextRowNumber not yet implemented. Need to deploy Apps Script first.\n` +
    `Entity type: ${entityType}\n` +
    `This function will call: getNext${entityType}Number() in Apps Script`
  );

  /*
   * Future implementation will look like:
   *
   * const response = await fetch(
   *   'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec',
   *   {
   *     method: 'POST',
   *     body: JSON.stringify({ action: 'getNextNumber', entityType }),
   *   }
   * );
   * const { number } = await response.json();
   * return number;
   */
}

/**
 * Generates a display ID based on entity type and row number
 * This is what the Google Sheets formula will generate, but we can preview it client-side
 *
 * Formula in Google Sheets: =IF(B2<>"", "LEA-"&TEXT(B2,"0000"), "")
 * Where B2 is the rowNumber column
 *
 * @param entityType - The type of entity
 * @param rowNumber - The sequential row number
 * @returns A formatted display ID (e.g., "LEA-0416")
 *
 * @example
 * const displayId = formatDisplayId('Lead', 416);
 * // Returns: "LEA-0416"
 */
export function formatDisplayId(entityType: EntityType, rowNumber: number): string {
  const prefix = DISPLAY_ID_PREFIXES[entityType];

  // Format number with leading zeros (4 digits)
  const formattedNumber = rowNumber.toString().padStart(4, '0');

  return `${prefix}-${formattedNumber}`;
}

/**
 * Complete ID generation for a new entity
 * Generates both UUID and gets next row number from Apps Script
 * Display ID will be generated by Google Sheets formula
 *
 * @param entityType - The type of entity being created
 * @returns Promise resolving to object with id and rowNumber
 *
 * @example
 * const { id, rowNumber } = await generateEntityIds('Lead');
 * // Returns: { id: "a3f7b9c1-...", rowNumber: 416 }
 * // displayId "LEA-0416" will be auto-generated by sheet formula
 */
export async function generateEntityIds(entityType: EntityType): Promise<{
  id: string;
  rowNumber: number;
}> {
  // Generate UUID immediately (client-side, no race condition)
  const id = generateUUID();

  // Get next row number from Apps Script (atomic increment)
  // This is called RIGHT BEFORE saving to minimize lost numbers
  const rowNumber = await getNextRowNumber(entityType);

  return { id, rowNumber };
}

/**
 * Validates that a UUID is in correct format
 *
 * @param uuid - The UUID string to validate
 * @returns true if valid UUID format, false otherwise
 */
export function isValidUUID(uuid: string): boolean {
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  return uuidRegex.test(uuid);
}

/**
 * Parses a display ID to extract the row number
 *
 * @param displayId - The display ID (e.g., "LEA-0416")
 * @returns The row number, or null if invalid format
 *
 * @example
 * const rowNumber = parseDisplayId("LEA-0416");
 * // Returns: 416
 */
export function parseDisplayId(displayId: string): number | null {
  const match = displayId.match(/^[A-Z]{3}-(\d{4})$/);
  if (!match) return null;

  return parseInt(match[1], 10);
}
